# Generated by Django 4.1.7 on 2023-03-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Tittle',
        ),
    ]
