# Generated by Django 4.1.7 on 2023-03-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_title_tittle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tittle',
            new_name='Title',
        ),
    ]
