# Generated by Django 4.1.7 on 2023-03-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_abt_description_contact_email_contact_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abt',
            name='name',
        ),
    ]
